### PR TITLE
Patch Sensors, particularly power and energy sensors to work with statistics. And patch climate controls

### PR DESCRIPTION
**Pull request by robigan**

### CODE REVIEW

**Comment by kubaceg** [comment]
What's the status? Can I help develop/test it?

**Comment by robigan** [comment]
@h4de5 Can u verify this pr?

**Comment by h4de5** [comment]
@robigan I am aware of it - there is a working branch with many more changes here: https://github.com/h4de5/home-assistant-vimar/tree/room_integrations

i need to check first if this would conflict.

**Comment by robigan** [comment]
Opened a new PR if you just want to quickly merge with what I said

**Comment by h4de5** [comment]
after checking again, this is already included in #48

**Pull request closed without merging**
